name: 'feature: 🚀 新機能追加'
description: 新機能追加タスク
labels: ['🚀 feature']
body:
  - type: textarea
    id: task-url
    attributes:
      label: NotionのタスクページURL
      placeholder: https://www.notion.so/~~~
    validations:
      required: true
  - type: textarea
    id: content
    attributes:
      label: その他特記事項
      placeholder: waiwai
    validations:
      required: false