export { TabHome } from '@/components/Tabs/TabHome'
export { Tab } from '@/components/Tabs/Tab'
export type { TabType } from '@/components/Tabs/Tab'
export { Tabs } from '@/components/Tabs/Tabs'
export { TabPanel } from '@/components/Tabs/TabPanel'
export type { TabPanelProps } from '@/components/Tabs/TabPanel'
export { TabList } from '@/components/Tabs/TabList'
export { TabTriplink } from '@/components/Tabs/TabTriplink'
export { TabDashboard } from '@/components/Tabs/TabDashboard'
export { TabTriplate } from '@/components/Tabs/TabTriplate'
