export { InputText } from '@/components/Inputs/InputText'
export { InputImage, type InputImageType } from '@/components/Inputs/InputImage'
export { InputTextArea } from '@/components/Inputs/InputTextArea'
export { InputLabel } from '@/components/Inputs/InputLabel'
export { InputErrorMessage } from '@/components/Inputs/InputErrorMessage'
