# https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-react-and-next

name: CI

on:
  push:
    paths:
      - front/**

jobs:
  CI:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18.13.0
        uses: actions/setup-node@v3
        with:
          node-version: '18.13.0'

      - name: 📥 Monorepo install
        uses: ./.github/actions/yarn-nm-install
      - name: Get yarn cache
        id: yarn-cache
        run: echo "YARN_CACHE_DIR=$(yarn cache dir)" >> "${GITHUB_OUTPUT}"
      
      - name: CI
        working-directory: ./front
        run: |
          yarn install --immutable
          yarn check:all
